config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  devise_for :khachhangs,
              path: '',
              path_names: {sign_in: 'login' ,sign_out: 'logout' ,edit: 'profile',sign_up: 'resgistration'},
              controllers: {omniauth_callbacks: 'omniauth_callbacks' }
  get "khachhangs/profile"
  put "khachhangs/update_info"
  get "khachhangs/update_info"

  resource :carts, only: [:show]

  resources :dondathangs
  get "dondathangs/success"
  get 'dondathangs/:madondathang/cancel', to: 'dondathangs#cancel_order', as: :cancel_order

  resources :chitietdathangs
  
  
  resources :sanphams

  post 'sanphams/add_to_cart', to:'sanphams#add_to_cart', as:  'add_to_cart'
  delete 'carts/remove_from_cart', to: 'carts#remove_from_cart', as: 'remove_from_cart'

  resources :loaisanphams

  get 'trangchu/index'
  get 'trangchu/huongdanchonsize'
  root "trangchu#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chitietdathang.rb
class Chitietdathang < ApplicationRecord

  belongs_to :dondathang
  belongs_to :chitietsp 

  before_save :set_into_money

  def into_money
    sanpham = Sanpham.find_by(masanpham: chitietsp.sanpham_id)
    sanpham.giaban * soluong
  end

  private
  def set_into_money
    self[:thanhtien] = into_money
  end
end

app/models/chitietkm.rb
class Chitietkm < ApplicationRecord

    belongs_to :sanpham
    belongs_to :khuyenmai

end

app/models/chitietsp.rb
class Chitietsp < ApplicationRecord
  self.primary_key = :machitietsp
  
  belongs_to :sanpham
  has_many :chitietdathangs
  has_and_belongs_to_many :dondathangs
  before_create :set_chitietsanpham_id

  validates :mausp, :size, :soluongton, :hinhanhsp ,presence: true
  mount_uploader :hinhanhsp, HinhanhspUploader

  def set_chitietsanpham_id
    self[:machitietsp] = "#{Time.now().to_i + rand(0..999) - rand(0..9999) + rand(0..999)}"
  end

end

app/models/cthoadonnhap.rb
class Cthoadonnhap < ApplicationRecord
  self.primary_key = :masanphamnhap
end

app/models/danhmuc.rb
class Danhmuc < ApplicationRecord
  self.primary_key = :madanhmuc
  self.name
  has_many :loaisanphams, dependent: :delete_all
  has_many :sanphams, through: :loaisanphams

  accepts_nested_attributes_for :loaisanphams
  before_create :set_danhmuc_id


  validates :madanhmuc, :tendanhmuc, presence: true

  def name
    return self.tendanhmuc
  end
  def set_danhmuc_id
    self[:madondathang] = "DM#{Time.now().to_i + rand(0..999) - rand(0..9999) + rand(0..999)}"
  end
end

app/models/dondathang.rb
class Dondathang < ApplicationRecord
  self.primary_key = :madondathang

  has_many :chitietdathangs

  belongs_to :khachhang

  before_create :set_order_id

  before_create :set_order_date
  before_create :set_delivery_date

  enum tinhtrang: {
    "Đã hủy" => 0,
    "Đơn hàng đang chờ xử lý" => 1,
    "Đơn hàng đã tiếp nhận" => 2,
    "Đơn hàng đang giao" => 3,
    "Giao hàng và thanh toán thành công" => 4,
  }

  def set_order_id
    self[:madondathang] = "DDH#{Time.now().to_i + rand(0..999) - rand(0..9999) + rand(0..999)}"
  end

  def set_order_date
    self[:ngaydathang] = Time.now()
  end

  def set_delivery_date
    self[:ngaygiaohang] = Time.now() + 432000
  end

end

app/models/hoadonnhap.rb
class Hoadonnhap < ApplicationRecord
  self.primary_key = :mahoadonnhap
end

app/models/khachhang.rb
class Khachhang < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  self.name
  has_many :dondathangs

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable , omniauth_providers: [:facebook, :google_oauth2]
  
  # validates :email, :hotenkhachhang, :diachi, :presence => true
  # validates :sodienthoai,:presence => true
  
  mount_uploader :anhdaidien, AvatarUploader

  def name
    return self.hotenkhachhang
  end

  def self.new_with_session params, session
    super.tap do |user|
      if data = session["devise.facebook_data"] &&
        session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def self.from_omniauth(auth)
    result = Khachhang.where(email: auth.info.email).first
    if result
      return result
    else
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
        user.hotenkhachhang = auth.info.name
        user.anhdaidien = auth.info.image
        user.uid = auth.uid
        user.provider = auth.provider
      end
    end
  end
end

app/models/khuyenmai.rb
class Khuyenmai < ApplicationRecord
    has_many :chitietkms

    before_create :set_km_id

    def set_km_id
        self[:makhuyenmai] = "DDH#{Time.now().to_i + rand(0..999) - rand(0..9999) + rand(0..999)}"
    end
end

app/models/loaisanpham.rb
class Loaisanpham < ApplicationRecord
  self.primary_key = :maloai
  self.name
  has_many :sanphams, dependent: :delete_all
  belongs_to :danhmuc
  validates :danhmuc, presence: true
  before_create :set_loaisanpham_id

  validates :maloai, :tenloai, :danhmuc_id , presence: true

  def name
    return self.tenloai
  end
  def set_loaisanpham_id
    self[:madondathang] = " LSP#{Time.now().to_i + rand(0..999) - rand(0..9999) + rand(0..999)}"
  end
end

app/models/nhacungcap.rb
class Nhacungcap < ApplicationRecord
  self.primary_key = :mancc
end

app/models/sanpham.rb
class Sanpham < ApplicationRecord
  self.primary_key = :masanpham
  self.name

  has_many :chitietsps, dependent: :delete_all
  belongs_to :loaisanpham, optional: true
  belongs_to :thuonghieu, optional: true
  before_create :set_sanpham_id
  accepts_nested_attributes_for :chitietsps

   
  validates :masanpham, :loaisanpham_id, :thuonghieu_id, :tensanpham, :giaban, presence: true

  def name
    return self.tensanpham
  end

  def set_sanpham_id
    self[:masanpham] = " SP#{Time.now().to_i + rand(0..999) - rand(0..9999) + rand(0..999)}"
  end
  


end

app/models/thuonghieu.rb
class Thuonghieu < ApplicationRecord
  has_many :sanphams
end

app/models/tintuc.rb
class Tintuc < ApplicationRecord
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  
  def show
    if session[:cart].nil?
      @order_items = []
    else
      @order_items = Chitietdathang.joins(:chitietsp).find(session[:cart])
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_order
    Dondathang.new
  end
  def avatar_url(user)
    if user.anhdaidien?
      user.anhdaidien  
    else
      gravatar_id = Digest::MD5::hexdigest(user.email).downcase
      "https://www.gravatar.com/avatar/#{gravatar_id}.jpg?d=identical&s=150"
    end
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/khachhangs_helper.rb
module KhachhangsHelper
end

app/helpers/sanphams_helper.rb
module SanphamsHelper
end

app/helpers/trangchu_helper.rb
module TrangchuHelper
end

app/views/carts/show.html.erb
<div class = "container-fluid col-md-10" style= "min-height: 580px;">
  <% if session[:cart].empty? %>
    <div lass="container" style="padding:300px; text-align:center">
      <%=link_to(image_tag('home.png'),root_path) %>
      <h4>Không có sản phẩm trong giỏ hàng !!!</h4>
      <div style="display: flex; color:rgb(255, 255, 255); justify-content: center;">
        <%= link_to "Tiếp tục mua sắm", root_path,{style: "background-color: rgb(255, 47, 47); padding: 5px 12px; color: #fff; border-radius: 10px; text-decoration:none;" } %>
      </div>
    </div>
  <% else %>
    <br>
    <h3 align="center"> CHI TIẾT GIỎ HÀNG </h3>
    <div class = "row">
      <div class = "col-md-8 col-sm-8">
        <table class= "table table-responsive">
          <thead class="thead-light">
            <tr>
              <th scope="col">Sản phẩm</th>
              <th scope="col">Tên sản phẩm</th>
              <th scope="col">Màu</th>
              <th scope="col">Size</th>
              <th scope="col">Số lượng</th>
              <th scope="col">Thành tiền</th>
              <th scope="col">Xóa</th>
            </tr>
          </thead>
            <tbody>
              <%@order_items.each do |item| %>
                <tr>
                  <td><%=image_tag item.chitietsp.hinhanhsp, style: "max-width:100px; max-height:130px;"%></td>
                  <td><%=item.chitietsp.sanpham.tensanpham%></td>
                  <td><%=item.chitietsp.mausp%></td>
                  <td align="center"><%=item.chitietsp.size%></td>
                  <td align="center"><%=item.soluong%></td>
                  <td align="center"><%= number_to_currency(item.thanhtien, precision: 0, unit: "", delimiter: ".", format: "%n %u")%></td>
                  <td align="center">
                    <%=link_to chitietdathang_path(item), method: :delete,data: { confirm: 'Xoá sản phẩm ' +item.chitietsp.sanpham.tensanpham + item.chitietsp.size + ' ?' }, remote: :true do %>
                      <section>
                        <span class="trash">
                          <span></span>
                          <i class="fa fa-trash" aria-hidden="true"></i>
                        </span>
                      </section>
                    <% end %>
                  </td>
                </tr>
              <%end%>
            </tbody>
        </table>
      </div>
      <div class = "col-md-4 col-sm-4">
        <div class ="col-md-12">
          <h5 class = "text-center">TỔNG TIỀN GIỎ HÀNG </h5>
          <table class="table">
            <tbody>
              <tr>
                <td id ="hidden-border">Tổng sản phẩm</td>
                <td id ="hidden-border"><%= @order_items.collect{|order_item| order_item.soluong}.sum%></td>
              </tr>
              <tr>
                <td id ="hidden-border">Thành Tiền</td>
                <td id ="hidden-border"><%= number_to_currency(@order_items.collect{|order_item| order_item.chitietsp.sanpham.giaban*order_item.soluong}.sum, precision: 0, unit: "đ", delimiter: ".", format: "%n %u")%></td>
              </tr>
            </tbody>
            <tfoot>
              <tr>
                <td>Tạm tình</td>
                <td class = "font-weight-bold"><%= number_to_currency(@order_items.collect{|order_item| order_item.chitietsp.sanpham.giaban*order_item.soluong}.sum, precision: 0, unit: "đ", delimiter: ".", format: "%n %u")%></td>
              </tr>
            </tfoot>
          </table>
          <p class="text-center">Quý khách vui lòng kiểm tra hóa đơn trước khi đặt hàng</p>
          <div class = "flex flex-column">
            <div class = "flex items-center topv">
              <%= link_to  "TIẾP TỤC MUA SẮM" , root_path , method: :get, class: "btn btn-outline-dark"%>
            </div>
            <div class = "flex items-center topv">
              <%= link_to  "ĐẶT HÀNG", new_dondathang_path , method: :get, class: "btn btn-outline-success"%>
            </div>
          </div>
        </div>
      </div>
    </div>
  <%end%>
</div>