config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  devise_for :khachhangs,
              path: '',
              path_names: {sign_in: 'login' ,sign_out: 'logout' ,edit: 'profile',sign_up: 'resgistration'},
              controllers: {omniauth_callbacks: 'omniauth_callbacks' }
  get "khachhangs/profile"
  put "khachhangs/update_info"
  get "khachhangs/update_info"

  resource :carts, only: [:show]

  resources :dondathangs
  get "dondathangs/success"
  get 'dondathangs/:madondathang/cancel', to: 'dondathangs#cancel_order', as: :cancel_order

  resources :chitietdathangs
  
  
  resources :sanphams

  post 'sanphams/add_to_cart', to:'sanphams#add_to_cart', as:  'add_to_cart'
  delete 'carts/remove_from_cart', to: 'carts#remove_from_cart', as: 'remove_from_cart'

  resources :loaisanphams

  get 'trangchu/index'
  get 'trangchu/huongdanchonsize'
  root "trangchu#index"
end

app/models/sanpham.rb
class Sanpham < ApplicationRecord
  self.primary_key = :masanpham
  self.name

  has_many :chitietsps, dependent: :delete_all
  belongs_to :loaisanpham, optional: true
  belongs_to :thuonghieu, optional: true
  before_create :set_sanpham_id
  accepts_nested_attributes_for :chitietsps

   
  validates :masanpham, :loaisanpham_id, :thuonghieu_id, :tensanpham, :giaban, presence: true

  def name
    return self.tensanpham
  end

  def set_sanpham_id
    self[:masanpham] = " SP#{Time.now().to_i + rand(0..999) - rand(0..9999) + rand(0..999)}"
  end
  


end

app/controllers/sanphams_controller.rb
class SanphamsController < ApplicationController
  before_action :set_product, only: %i[show]
  before_action :initialize_session
  before_action :authenticate_khachhang!, only: :add_to_cart

  require "will_paginate/array"
  # GET /products
  # GET /products.json
  def index
    @products = Sanpham.all
    # Show product by conditions
    if params[:pro] == "Sale"
      showProSale
    elsif params[:sex].nil?
      showProducts
    elsif params[:name].nil?
      showProGender
    else
      showProType
    end
    showBrands if params[:brand].present?
    # Sort prices
    unless params[:sortPrice].nil?
      @array_product_follow_category = @array_product_follow_category.order(giaban: params[:sortPrice])
    end
  end

  def showProSale
    @array_product_follow_category = []
    @products.each do |sp|
      pro_cate = Sanpham.where.not(masanpham: sp.masanpham, giakhuyenmai: [nil, 0])
      @array_product_follow_category << pro_cate
    end
    @array_product_follow_category.delete_if(&:blank?)
    @array_product_follow_category = @array_product_follow_category.paginate(page: params[:page], per_page: 20)
    @bread = params[:pro]
  end

  def showProducts
    @array_product_follow_category = []
    @products.each do |sp|
      pro_cate = Sanpham.where(masanpham: sp.masanpham)
      @array_product_follow_category << pro_cate
    end
    @array_product_follow_category.delete_if(&:blank?)
    @array_product_follow_category = @array_product_follow_category.paginate(page: params[:page], per_page: 20)
    @bread = "Sản phẩm"
  end

  def showProGender
    @array_product_follow_category = []
    category = Danhmuc.includes(loaisanphams: :sanphams).where(tendanhmuc: params[:sex])
    category.each do |cate|
      pro_cate = cate.sanphams
      @array_product_follow_category << pro_cate
    end
    @array_product_follow_category.delete_if(&:blank?)
    @array_product_follow_category = @array_product_follow_category.paginate(page: params[:page], per_page: 20)
    @bread = params[:sex]
  end

  def showProType
    @array_product_follow_category = []
    @products.each do |sp|
      pro_cate = Sanpham.where(masanpham: sp.masanpham, loaisanpham_id: params[:id])
      @array_product_follow_category << pro_cate
    end
    @array_product_follow_category.delete_if(&:blank?)
    @array_product_follow_category = @array_product_follow_category.paginate(page: params[:page], per_page: 20)
    @bread = params[:name]
    @gen = params[:sex]
  end

  def showBrands
    @array_product_follow_category = []
    brand = Thuonghieu.includes(:sanphams).where(tenthuonghieu: params[:brand])
    brand.each do |br|
      pro_cate = br.sanphams
      @array_product_follow_category << pro_cate
    end
    @array_product_follow_category.delete_if(&:blank?)
    @array_product_follow_category = @array_product_follow_category.paginate(page: params[:page], per_page: 20)
    @bread = params[:brand]
  end

  def show
    @product = Sanpham.includes(:chitietsps).find(params[:id])
    @product_category_sames = Sanpham.includes(:chitietsps).where(loaisanpham_id: @product.loaisanpham_id).limit(6)
    @product_detail = Chitietsp.find_by(sanpham_id: @product.masanpham, mausp: params[:color])
    @product_details_all = Chitietsp.where(sanpham_id: @product.masanpham, mausp: params[:color])
    product_same_name = Chitietsp.where(sanpham_id: @product.masanpham)

    @image_product_same = {}
    product_same_name.each do |product_detail|
      @image_product_same[product_detail.mausp] = product_detail.hinhanhsp
    end
    
    #new line item
    @order_item = current_order.chitietdathangs.new
    @order_item.valid?
  end
  
  private
  def initialize_session
    session[:cart] ||= [] 
   end

  def set_product
    @product = Sanpham.find(params[:id])
  end
end

app/helpers/sanphams_helper.rb
module SanphamsHelper
end

app/views/sanphams/_chitietsanpham.html.erb
<div class="col-md-4">
  <div>
    <%=image_tag @product_detail.hinhanhsp ,class: "img-fluid"%>
  </div>
</div>
<div class="col-md-8">
  <div class="ditem">
    <div class="row" >
      <div class="col-md-12" >
        <h3 class="text"><%=@product.tensanpham%></h3>
        <h4 class="price-detail">
          <% if @product.giakhuyenmai.nil? || @product.giakhuyenmai == 0 %>
            <%= number_to_currency(@product.giaban, precision: 0, unit: "", delimiter: ".", format: "%n %u")%><sup style="font-style: unset;">đ</sup>
          <% else %>
            <%= number_to_currency(@product.giakhuyenmai, precision: 0, unit: "", delimiter: ".", format: "%n %u")%><sup style="font-style: unset;">đ</sup> <span style="text-decoration:line-through; color:#ff0000"><%= number_to_currency(@product.giaban, precision: 0, unit: "", delimiter: ".", format: "%n %u") %><sup style="font-style: unset;">đ</sup></span>
          <% end %>
        </h5>
        <div class= "flex flex-column">
          <div class="flex items-center">
            <span class="text-black">Màu sắc:</span>
            <span class="product-color-text"><%= @product_detail.mausp %></span><label class="required"><em>&nbsp;*</em></label>
          </div>
          <div class="flex items-center">
            <span class="text-black">Size:</span>
          </div>
          <%=form_for @order_item, as: :product_detail do |f|%>
            <div class="flex items-center top">
              <%= f.hidden_field :sanpham_id, :value => @product.masanpham %>
              <%= f.hidden_field :mausp, :value => @product_detail.mausp %>
              <div class="row" id="product_size">
                <%@product_details_all.each do |product_detail|%>
                  <%=radio_button_tag :product_size, product_detail.size, false, {disabled: (product_detail.soluongton <= 0 ? true : false)}%><label for="<%="product_size_" + product_detail.size%>" class="product-size"><%=product_detail.size%></label>
                <%end%>
              </div>
              <div class="flex items-center top">
                <span class="text-black">Số lượng:&nbsp;&nbsp;&nbsp;&nbsp;</span><%=f.number_field :soluong, value: 1 , min: 1, required: true%></p>
              </div>
            </div>    
            <div class="flex items-center top">
              <i class="far fa-edit">&nbsp;&nbsp;<%= link_to 'Hướng dẫn chọn size', trangchu_huongdanchonsize_path, class: "fw-normal"%></i>
            </div>        
            <% if @product.giaban <= 0 %>
              <td style=" padding-left:86px">
                <h5 style="color:#ff0000"> Hết Hàng </h5>
              </td>
            <% else %>
              <%= f.submit "Thêm Vào Giỏ Hàng", class: "button_to buy", id: "js-addItemToCart" %>
              <%= f.submit "Mua ngay",class: "button_to now"%>
            <%end%>
          <%end%>
        </div>
      </div>
    </div>
    <hr>
    <div class="row">
      <%@image_product_same.each do |key, values|%>
        <div class="col-4 col-sm-3">
          <div class="vitem">
            <%=link_to(image_tag( values ,{style: "width:100px; height:130px;"}),sanpham_path(@product, color: key))%>
            <p><%=key%></p>
          </div>
        </div>
      <%end%>
    </div>
    <hr>
  </div>
</div>

app/views/sanphams/_ds_sanpham.html.erb
<div class="row">
  <% if @array_product_follow_category.empty? %>
  <div class="container" style="padding:300px; text-align:center">
    <%=link_to(image_tag('home.png'),root_path) %>
      <h4>Không có sản phẩm !!!</h4>
    <div style="display: flex; color:rgb(255, 255, 255); justify-content: center;">
      <%= link_to "Tiếp tục mua sắm", root_path,{style: "background-color: rgb(255, 47, 47); padding: 5px 12px; color: #fff; border-radius: 10px;text-decoration:none;" } %>
    </div>
  </div>
  <% else %>
  <%@array_product_follow_category.each do |array_product_follow_category|%>
  <%array_product_follow_category.each do |product_follow_category|%>
  <div class="col-xs-6 col-sm-3 col-md-3">
    <div class="pitem">
      <!-- Show product by image -->
      <input type="hidden" value="-420000">
      <%@product_details = Sanpham.includes(:chitietsps).where(masanpham: product_follow_category.masanpham).last%>
      <%=link_to (image_tag @product_details.chitietsps.last.hinhanhsp ,class: "img-fluid d-block w-100"), sanpham_path(@product_details, color: @product_details.chitietsps.last.mausp)%>
      <!-- all image details for product class = "image_border" -->
      <div class="row mt-2">
        <div class="col-12 col-sm-12">
          <%product_details_all = Chitietsp.where(sanpham_id: product_follow_category.masanpham)%>
          <%hash_image = {}%>
          <%product_details_all.each do |details_of_product|%>
          <%hash_image[details_of_product.mausp] = details_of_product.hinhanhsp%>
          <%end%>
          <%hash_image.each do |key, values|%>
          <div class="pull-left circular">
            <%= link_to ( image_tag values, class: "small_image_color"), sanpham_path(@product_details, color:key)%>
          </div>
          <%end%>
        </div>
      </div>
      <div class="row mt-2">
        <div class="col-12 col-sm-12 font-weight-bold">
          <%=link_to product_follow_category.tensanpham, sanpham_path(@product_details, color: @product_details.chitietsps.last.mausp),  class: "fw-normal"%>
        </div>
        <div class="col-12 col-sm-12">
          <p class="price">
            <%if product_follow_category.giakhuyenmai.nil? || product_follow_category.giakhuyenmai == 0 %>
            <span>
              <%= number_to_currency(product_follow_category.giaban, precision: 0, unit: "", delimiter: ".", format: "%n %u")%><sup
                style="font-style: unset;">đ</sup></span>
            <%else%>
            <span
              style="text-decoration:line-through"><%= number_to_currency(product_follow_category.giaban, precision: 0, unit: "", delimiter: ".", format: "%n %u")%><sup
                style="font-style: unset;">đ</sup></span>
            <span
              style="color:#ff0000"><%= number_to_currency(product_follow_category.giakuyenmai, precision: 0, unit: "", delimiter: ".", format: "%n %u")%><sup
                style="font-style: unset;">đ</sup></span>
            <%end%>
          </p>
        </div>
      </div>
    </div>
  </div>
  <%end%>
  <%end%>
  <%end%>
</div>
<!-- Pagination -->
<div class="row mb-2">
  <div class="col-7 text-right">
    <%=will_paginate @array_product_follow_category, class: "justify-content-end" , style: "color:orange"%>
  </div>
</div>

app/views/sanphams/_form.html.erb
<%= form_with(model: sanpham, local: true) do |form| %>
  <% if sanpham.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sanpham.errors.count, "error") %> prohibited this sanpham from being saved:</h2>

      <ul>
      <% sanpham.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sanphams/_sanphamtuongtu.html.erb
<div class="breadcrumb">
  <h5>SẢN PHẨM TƯƠNG TỰ</h5>
</div>
<div class="row">
  <%@product_category_sames.each do |el,index|%>
      <% if index == 12 %>
        <%break%>
      <%end%>
      <div class="col-xs-12 col-md-2">
        <%=link_to(image_tag(el.chitietsps.first.hinhanhsp ,style: "width:100px; height:130px;"), sanpham_path(el, color: el.chitietsps.first.mausp)) %>
        <p><%=link_to el.tensanpham, sanpham_path(el, color: el.chitietsps.first.mausp), class: "fw-normal" %></p>
      </div>
  <%end%>
</div>

app/views/sanphams/cart.html.erb
<div class = "container-fluid col-md-8" style= "min-height: 580px;">
<br>
  <div class = "row">
    <div class = "col-md-8 col-sm-8">
      <table class= "table table-responsive">
        <thead class="thead-light">
          <tr>
            <th scope="col">Sản phẩm</th>
            <th scope="col">Tên sản phẩm</th>
            <th scope="col">Màu</th>
            <th scope="col">Size</th>
            <th scope="col">Số lượng</th>
            <th scope="col">Thành tiền</th>
            <th scope="col">Thao tác</th>
          </tr>
        </thead>
        <%@cart.each do |product_detail|%>
        <tbody>
          <tr>
            <td><%=image_tag product_detail.hinhanhsp, :style => "max-width:100px; max-height:130px;"%></td>
            <td><%=product_detail.sanpham.tensanpham%></td>
            <td><%=product_detail.mausp%></td>  
            <td><%=product_detail.size%></td>
            <td>
            <div class ="row">
              <div class="input-group"> 
                <span class="input-group-btn">    
                  <button type="button" class="btn btn-default btn-number" disabled="disabled" data-type="minus" data-field="quant[1]" > 
                    <span class="fa fa-minus"></span> 
                  </button>    
                </span> 
                <input name="quant[1]" id="number" class="form-control input-number" value="1" min="1" max="200" type="text"> 
                <span class="input-group-btn">    
                  <button type="button" class="btn btn-default btn-number" data-type="plus" data-field="quant[1]" > 
                    <span class="fa fa-plus"></span> 
                  </button>    
                </span> 
            </div>
            </td>
            <td id="price"> <%= number_to_currency(product_detail.sanpham.giaban, precision: 0, unit: "", delimiter: ".", format: "%n %u")%><sup
              style="font-style: unset;">đ</sup></td>
            <td>
              <%=link_to "Xóa", remove_from_cart_path(product_detail), method: :delete%>
            </td>
        </tbody>
        <%end%>
      </table>
    </div>
    <div class = "col-md-4 col-sm-4">
      <div class ="col-md-12">
          <h5 class = "text-center">TỔNG TIỀN GIỎ HÀNG </h5>
        <table>
          <tbody>
            <tr>
              <td class = "col-sm-8">Tổng sản phẩm</td>
              <td class = "col-sm-4">...</td>
            </tr>
            <tr>
              <td class = "col-sm-8">Thành Tiền</td>
              <td class = "col-sm-4" id="total-price"><sup style="font-style: unset;">đ</sup></td>
            </tr>
          </tbody>
          <tfoot>
            <tr>
              <td class = "col-sm-8">Tạm tình</td>
              <td class = "col-sm-4 font-weight-bold">150.000<sup style="font-style: unset;">đ</sup></td>
            </tr>
          </tfoot>
        </table>
        <br>
        <p class="text-center">Bạn sẽ được miễn phí ship khi đơn hàng của bạn có tổng giá trị trên 3.000.000<sup>đ</sup></p>
        <div class = "row container">
          <div>
            <%= button_to  "TIẾP TỤC MUA SẮM"%>
          </div>
          <div>
            <%= button_to  "THANH TOÁN"%>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/sanphams/edit.html.erb
<h1>Editing Sanpham</h1>

<%= render 'form', sanpham: @sanpham %>

<%= link_to 'Show', @sanpham %> |
<%= link_to 'Back', sanphams_path %>

app/views/sanphams/index.html.erb
<div class="container-fluid col-md-10">
  <div class="row">
    <div class="col-12">
      <div class="breadcrumb">
        <%=link_to image_tag('home.png'), root_path %>
        <span class="mx-2 mb-0">/</span>
        <%if @gen.present?%>
          <%= link_to @gen, sanphams_path(sex: @gen), class: "fw-normal" %>
          <span class="mx-2 mb-0">/</span>
          <strong class="text-black"><%=@bread%></strong>
        <%else%>
          <strong class="text-black"><%=@bread%></strong>
        <%end%>
      </div>
    </div>
  </div>
  <!-- <div class="row mb-4">
    <div class="col-md-6 col-sm-12 col-6">
      <div class="row">
        <div class="col-md-3 col-sm-6 col-xs-12 filter_show">
          <%# <div class="col-md-12"><span>Bộ lọc</span><span class="caret pull-right"></span></div> %>
        </div>
      </div>
    </div>
    <div class="col-md-6 col-sm-12 col-12 text-right">
      <div class="row p">
        <div class="col-mb-2"><span style="font-weight:bold">Sắp xếp:</span></div>
        <div class="col-md-5"><input data-sorttype="asc" type="radio" name="s_prices" value="Ascending"> Giá từ thấp đến cao</div>
        <div class="col-md-5"><input data-sorttype="desc" type="radio" name="s_prices" value="Descrease"> Giá từ cao đến thấp</div>
      </div>
    </div>
  </div> -->
  <!-- Show products by condition -->
  <div class="sort_paginate_ajax">
    <%= render "ds_sanpham"%>
  </div>
</div>

app/views/sanphams/index.js.erb
$('.sort_paginate_ajax').html("<%= escape_javascript(render("ds_sanpham"))%>");
$('.sort_paginate_ajax .justify-content-end a').attr('data-remote', 'true');

app/views/sanphams/new.html.erb
<h1>New Sanpham</h1>

<%= render 'form', sanpham: @sanpham %>

<%= link_to 'Back', sanphams_path %>

app/views/sanphams/show.html.erb
<div class="container-main container-fluid col-11">
  <div class="row">
    <div class="col-12">
      <div class="breadcrumb" style="weight: 945px; fornt-height:35px;">
        <%=link_to(image_tag( 'home.png'),root_path) %>
        <span class="mx-2 mb-0">/</span>
        <strong class="text-black"><%=@product.tensanpham%></strong>
      </div>
    </div>
  </div>
  <br>
  <div class = "row">
    <%=render "chitietsanpham"%>
  </div>
  <br>
  <div class="row">
    <div class="col-sm-12">
      <div class="breadcrumb">
        <h5>MÔ TẢ SẢN PHẨM</h5>
      </div>
      <p><%=raw @product.mota%></p>
    </div>
  </div>
  <%=render "sanphamtuongtu"%>
</div>