config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  devise_for :khachhangs,
              path: '',
              path_names: {sign_in: 'login' ,sign_out: 'logout' ,edit: 'profile',sign_up: 'resgistration'},
              controllers: {omniauth_callbacks: 'omniauth_callbacks' }
  get "khachhangs/profile"
  put "khachhangs/update_info"
  get "khachhangs/update_info"

  resource :carts, only: [:show]

  resources :dondathangs
  get "dondathangs/success"
  get 'dondathangs/:madondathang/cancel', to: 'dondathangs#cancel_order', as: :cancel_order

  resources :chitietdathangs
  
  
  resources :sanphams

  post 'sanphams/add_to_cart', to:'sanphams#add_to_cart', as:  'add_to_cart'
  delete 'carts/remove_from_cart', to: 'carts#remove_from_cart', as: 'remove_from_cart'

  resources :loaisanphams

  get 'trangchu/index'
  get 'trangchu/huongdanchonsize'
  root "trangchu#index"
end

app/models/dondathang.rb
class Dondathang < ApplicationRecord
  self.primary_key = :madondathang

  has_many :chitietdathangs

  belongs_to :khachhang

  before_create :set_order_id

  before_create :set_order_date
  before_create :set_delivery_date

  enum tinhtrang: {
    "Đã hủy" => 0,
    "Đơn hàng đang chờ xử lý" => 1,
    "Đơn hàng đã tiếp nhận" => 2,
    "Đơn hàng đang giao" => 3,
    "Giao hàng và thanh toán thành công" => 4,
  }

  def set_order_id
    self[:madondathang] = "DDH#{Time.now().to_i + rand(0..999) - rand(0..9999) + rand(0..999)}"
  end

  def set_order_date
    self[:ngaydathang] = Time.now()
  end

  def set_delivery_date
    self[:ngaygiaohang] = Time.now() + 432000
  end

end

app/controllers/dondathangs_controller.rb
class DondathangsController < ApplicationController
  before_action :set_dondathang, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_khachhang!, only: [:new]
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart

  def index
    if khachhang_signed_in?
      @orders = current_khachhang.dondathangs
    end
  end

  def show
    @order = Dondathang.find(params[:id])
    @order_items = Chitietdathang.joins(:chitietsp).where(dondathang_id: @order.madondathang)
  end

  #update attribute tinhtrang = "cancel"
  def cancel_order
    @order = Dondathang.find(params[:madondathang])
    @order.update_column(:tinhtrang, 0)
    redirect_to dondathangs_path
  end

  def new 
    @dondathang = Dondathang.new
    @order_items = Chitietdathang.joins(:chitietsp).find(session[:cart])
  end

  def create
    cart = session[:cart]
    @dondathang = current_khachhang.dondathangs.create(dondathang_params)
    respond_to do |format|
      if @dondathang.save
        @order_items = Chitietdathang.joins(:chitietsp).find(session[:cart])
        @order_items.each  do |chitietdathang| 
          chitietdathang.dondathang_id = @dondathang.id
          chitietdathang.save
          chitietsanpham = Chitietsp.find(chitietdathang.chitietsp_id)
          # binding.pry
          chitietsanpham.update_attribute(:soluongton, chitietsanpham.soluongton - chitietdathang.soluong)
          
        end
        
        session[:cart].clear
        OrderMailer.received(@dondathang).deliver_later
        format.html { render "dondathangs/success" }
        format.json { render :show, status: :created, location: @dondathang }
      end
    end
  end

  def update
    respond_to do |format|
      if @dondathang.update(dondathang_params)
        format.html { redirect_to @dondathang}
        format.json { render :show, status: :ok, location: @dondathang }
      else
        format.html { render :edit }
        format.json { render json: @dondathang.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dondathang
      @dondathang = Dondathang.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def dondathang_params
      params.require(:dondathang).permit(:diachigiaohang)
    end

    def invalid_cart
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to root_path, notice: "Invalid cart"
    end
end

app/helpers/dondathangs_helper.rb
module DondathangsHelper
end

app/views/dondathangs/_form.html.erb
<br>
<article class="card">
  <header class="card-header" style="font-size: 25px">
   Chi tiết đơn hàng #<%=@order.madondathang%> - <b><%=@order.tinhtrang%></b>
  </header>
  <div class="card-body">
    <article class="card">
      <div class="card-body row">
        <div class="col"> <strong>Thời gian đặt hàng:</strong> <br><%=@order.ngaydathang.strftime("%d-%m-%Y")%></div>
        <div class="col"> <strong>Người đặt hàng:</strong> <br> <%=current_khachhang.hotenkhachhang%> , <i class="fa fa-phone"></i> <%=current_khachhang.sodienthoai%></div>
        <div class="col"> <strong>Địa chỉ giao hàng:</strong> <br> <%=@order.diachigiaohang%></div>
      </div>
    </article>
    <hr>
      <div class="card-body row">
        <div class="col"> <strong>Sản Phẩm:</strong> </div>
        <div class="col"> <strong>Size:</strong>  </div>
        <div class="col"> <strong>Màu:</strong>  </div>
        <div class="col"> <strong>Giá:</strong> </div>
        <div class="col"> <strong>Số Lượng:</strong> </div>
         <div class="col"> <strong>Thành Tiền:</strong> </div>
      </div>
      <% @order_items.each do |item| %>
      <div class="card-body row">
        <div class="col"> <%= item.chitietsp.sanpham.tensanpham %> </div>
        <div class="col"> <%= item.chitietsp.size %> </div>
        <div class="col"> <%= item.chitietsp.mausp %>  </div>
        <div class="col"> <%= item.chitietsp.sanpham.giaban %>  </div>
        <div class="col"> <%= item.soluong %>  </div>
        <div class="col"> <%= item.soluong * item.chitietsp.sanpham.giaban %>  </div>
      </div>
      <% end %>
    <hr>
    <h5 class = "col-md-10 text-right">Tổng Tiền: <%=@order_items.collect{|item| item.soluong * item.chitietsp.sanpham.giaban}.sum%></h5>
  </div>
  <div class="card-footer">
    <%if @order.tinhtrang == "Đơn hàng đang chờ xử lý" || @order.tinhtrang == "Đơn hàng đã tiếp nhận"%>
      <%=link_to "Hủy", cancel_order_path(@order.madondathang), class: "btn btn-danger" %>
    <%end%>
  </div>
</article>

app/views/dondathangs/edit.html.erb
<h1>Editing Dondathang</h1>

<%= render 'form', dondathang: @dondathang %>

<%= link_to 'Show', @dondathang %> |
<%= link_to 'Back', dondathangs_path %>

app/views/dondathangs/index.html.erb
<div class = "container" style= " min-height: 520px;">
  <h4 class = "card-header">Đơn hàng của tôi</h4>
  <div class = "table-responsive text-nowrap">
    <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">Mã đơn hàng</th>
          <th scope="col">Ngày mua</th>
          <th scope="col">Tổng tiền</th>
          <th scope="col">Trạng thái đơn hàng</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <% unless @orders.nil? %>
        <%@orders.each do |order|%>
          <tbody>
            <tr>
              <td><%=order.madondathang%></td>
              <td><%=order.ngaydathang.strftime("%d/%m/%Y")%></td>
              <td><%order_item =  Chitietdathang.joins(:chitietsp).where(dondathang_id: order.madondathang)%>
                <%= number_to_currency(order_item.collect{ |item| item.soluong * item.chitietsp.sanpham.giaban}.sum, precision: 0, unit: "", delimiter: ".", format: "%n %u")%>
              </td>
              <td><%=order.tinhtrang%></td>
              <td></td>
              <td>
                <%=link_to "Chi tiết đơn hàng", dondathang_path(order ), class: "btn btn-info"%>
              </td>
            </tr>
          </tbody>
        <%end%>
      <%end%>
    </table>
  </div>
</div>

app/views/dondathangs/new.html.erb
<br>
<div class = "container col-xl-10 align-self-center">
  <%=form_for @dondathang do |f|%>
  <div class="row">
    <div class="col-sm-8 col-md-4 ">
      <h4>Địa chỉ giao hàng</h4>
      <br>
      <div class="card bg-light border-info mb-3" style="max-width: 28rem;">
        <div class="card-body">
          <p class="card-text">Họ và tên: <%=current_khachhang.hotenkhachhang%></p>
          <p class="card-text">
            <%=f.label :"Địa chỉ giao hàng: "%>
            <%=f.text_field :diachigiaohang, :value => current_khachhang.diachi %>
          </p>
          <p class="card-text">Số điện thoại: <%=current_khachhang.sodienthoai%></p>
        </div>
      </div>
    </div>
    <div class = "col-md-4 col-sm-4">
      <div class ="col-md-12">
        <h5 class = "text-center">Đơn hàng (<%=@order_items.collect{|order_item| order_item.soluong}.sum%> sản phẩm)</h5>
        <br>
        <table>
          <tbody>
            <%@order_items.each do |item|%>
              <tr>
                <td class = "col-sm-8"><%=item.soluong%>X - <%=item.chitietsp.sanpham.tensanpham%>-<%=item.chitietsp.size%></td>
                <td class = "col-sm-4"><%= number_to_currency(item.thanhtien, precision: 0, unit: "", delimiter: ".", format: "%n %u")%></td>
              </tr>
            <%end%>
          </tbody>
          <tfoot>
            <tr>
              <td class = "col-sm-8">Tổng tiền</td>
              <td class = "col-sm-4 font-weight-bold"><%= number_to_currency(@order_items.collect{|order_item| order_item.chitietsp.sanpham.giaban*order_item.soluong}.sum, precision: 0, unit: "đ", delimiter: ".", format: "%n %u")%></td>
            </tr>
          </tfoot>
        </table>
        <br>
        <p class="text-center">Quý khách vui lòng kiểm tra hóa đơn trước khi đặt hàng</p>
        <%=form_for @dondathang do |f|%>
          <%f.submit "ĐẶT MUA" , class: "btn btn-danger btn-lg btn-block"%>
        <%end%>
      </div>  
    </div>
  </div>
  <%end%>
</div>

app/views/dondathangs/show.html.erb
<div class="container" >
  <%=render"dondathangs/form"%>
  <div class ="btn btn-warning">
    <i class="fa fa-chevron-left" style ="color: #000; "></i>
    <%=link_to "Back", dondathangs_path , style:"color: #000; "%>
  </div>
</div>

app/views/dondathangs/success.html.erb
<br>
<div class="container">
  <div class= "card">
    <div class = "card-header center">
      <div>
        <%=image_tag "order_s.png", class:"rounded mx-auto d-block", style: " wieght: 150px; height: 150px;"%>
      </div>
      <br>
      <h4 class = "d-flex justify-content-center text-success">Cảm ơn quý khách đã mua hàng</h4>
    </div>
    <div class = "card-body">
      <p class = "d-flex justify-content-center">Đơn hàng của quý khách đã được tiếp nhận</p>
      <p class = "d-flex justify-content-center">Chi tiết đơn hàng của quý khách đã được gửi về địa chỉ Email: <%=current_khachhang.email%></p>
      <p class = "d-flex justify-content-center">Mọi thắc mắc xin liên hệ Hotline: 0357502346</p>
    </div>
    <div class = "card-footer">
      <%=link_to "Tiếp tục mua sắm", root_path%>
    </div>
  </div>
</div>