config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  devise_for :khachhangs,
              path: '',
              path_names: {sign_in: 'login' ,sign_out: 'logout' ,edit: 'profile',sign_up: 'resgistration'},
              controllers: {omniauth_callbacks: 'omniauth_callbacks' }
  get "khachhangs/profile"
  put "khachhangs/update_info"
  get "khachhangs/update_info"

  resource :carts, only: [:show]

  resources :dondathangs
  get "dondathangs/success"
  get 'dondathangs/:madondathang/cancel', to: 'dondathangs#cancel_order', as: :cancel_order

  resources :chitietdathangs
  
  
  resources :sanphams

  post 'sanphams/add_to_cart', to:'sanphams#add_to_cart', as:  'add_to_cart'
  delete 'carts/remove_from_cart', to: 'carts#remove_from_cart', as: 'remove_from_cart'

  resources :loaisanphams

  get 'trangchu/index'
  get 'trangchu/huongdanchonsize'
  root "trangchu#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chitietdathang.rb
class Chitietdathang < ApplicationRecord

  belongs_to :dondathang
  belongs_to :chitietsp 

  before_save :set_into_money

  def into_money
    sanpham = Sanpham.find_by(masanpham: chitietsp.sanpham_id)
    sanpham.giaban * soluong
  end

  private
  def set_into_money
    self[:thanhtien] = into_money
  end
end

app/models/chitietkm.rb
class Chitietkm < ApplicationRecord

    belongs_to :sanpham
    belongs_to :khuyenmai

end

app/models/chitietsp.rb
class Chitietsp < ApplicationRecord
  self.primary_key = :machitietsp
  
  belongs_to :sanpham
  has_many :chitietdathangs
  has_and_belongs_to_many :dondathangs
  before_create :set_chitietsanpham_id

  validates :mausp, :size, :soluongton, :hinhanhsp ,presence: true
  mount_uploader :hinhanhsp, HinhanhspUploader

  def set_chitietsanpham_id
    self[:machitietsp] = "#{Time.now().to_i + rand(0..999) - rand(0..9999) + rand(0..999)}"
  end

end

app/models/cthoadonnhap.rb
class Cthoadonnhap < ApplicationRecord
  self.primary_key = :masanphamnhap
end

app/models/danhmuc.rb
class Danhmuc < ApplicationRecord
  self.primary_key = :madanhmuc
  self.name
  has_many :loaisanphams, dependent: :delete_all
  has_many :sanphams, through: :loaisanphams

  accepts_nested_attributes_for :loaisanphams
  before_create :set_danhmuc_id


  validates :madanhmuc, :tendanhmuc, presence: true

  def name
    return self.tendanhmuc
  end
  def set_danhmuc_id
    self[:madondathang] = "DM#{Time.now().to_i + rand(0..999) - rand(0..9999) + rand(0..999)}"
  end
end

app/models/dondathang.rb
class Dondathang < ApplicationRecord
  self.primary_key = :madondathang

  has_many :chitietdathangs

  belongs_to :khachhang

  before_create :set_order_id

  before_create :set_order_date
  before_create :set_delivery_date

  enum tinhtrang: {
    "Đã hủy" => 0,
    "Đơn hàng đang chờ xử lý" => 1,
    "Đơn hàng đã tiếp nhận" => 2,
    "Đơn hàng đang giao" => 3,
    "Giao hàng và thanh toán thành công" => 4,
  }

  def set_order_id
    self[:madondathang] = "DDH#{Time.now().to_i + rand(0..999) - rand(0..9999) + rand(0..999)}"
  end

  def set_order_date
    self[:ngaydathang] = Time.now()
  end

  def set_delivery_date
    self[:ngaygiaohang] = Time.now() + 432000
  end

end

app/models/hoadonnhap.rb
class Hoadonnhap < ApplicationRecord
  self.primary_key = :mahoadonnhap
end

app/models/khachhang.rb
class Khachhang < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  self.name
  has_many :dondathangs

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable , omniauth_providers: [:facebook, :google_oauth2]
  
  # validates :email, :hotenkhachhang, :diachi, :presence => true
  # validates :sodienthoai,:presence => true
  
  mount_uploader :anhdaidien, AvatarUploader

  def name
    return self.hotenkhachhang
  end

  def self.new_with_session params, session
    super.tap do |user|
      if data = session["devise.facebook_data"] &&
        session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def self.from_omniauth(auth)
    result = Khachhang.where(email: auth.info.email).first
    if result
      return result
    else
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
        user.hotenkhachhang = auth.info.name
        user.anhdaidien = auth.info.image
        user.uid = auth.uid
        user.provider = auth.provider
      end
    end
  end
end

app/models/khuyenmai.rb
class Khuyenmai < ApplicationRecord
    has_many :chitietkms

    before_create :set_km_id

    def set_km_id
        self[:makhuyenmai] = "DDH#{Time.now().to_i + rand(0..999) - rand(0..9999) + rand(0..999)}"
    end
end

app/models/loaisanpham.rb
class Loaisanpham < ApplicationRecord
  self.primary_key = :maloai
  self.name
  has_many :sanphams, dependent: :delete_all
  belongs_to :danhmuc
  validates :danhmuc, presence: true
  before_create :set_loaisanpham_id

  validates :maloai, :tenloai, :danhmuc_id , presence: true

  def name
    return self.tenloai
  end
  def set_loaisanpham_id
    self[:madondathang] = " LSP#{Time.now().to_i + rand(0..999) - rand(0..9999) + rand(0..999)}"
  end
end

app/models/nhacungcap.rb
class Nhacungcap < ApplicationRecord
  self.primary_key = :mancc
end

app/models/sanpham.rb
class Sanpham < ApplicationRecord
  self.primary_key = :masanpham
  self.name

  has_many :chitietsps, dependent: :delete_all
  belongs_to :loaisanpham, optional: true
  belongs_to :thuonghieu, optional: true
  before_create :set_sanpham_id
  accepts_nested_attributes_for :chitietsps

   
  validates :masanpham, :loaisanpham_id, :thuonghieu_id, :tensanpham, :giaban, presence: true

  def name
    return self.tensanpham
  end

  def set_sanpham_id
    self[:masanpham] = " SP#{Time.now().to_i + rand(0..999) - rand(0..9999) + rand(0..999)}"
  end
  


end

app/models/thuonghieu.rb
class Thuonghieu < ApplicationRecord
  has_many :sanphams
end

app/models/tintuc.rb
class Tintuc < ApplicationRecord
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/khachhangs_helper.rb
module KhachhangsHelper
end

app/helpers/sanphams_helper.rb
module SanphamsHelper
end

app/helpers/trangchu_helper.rb
module TrangchuHelper
end

app/views/common/_footer.html.erb
<div id="footer_frame">
  <div class="footer">
    <%= image_tag 'lg.jpeg', alt: 'CaseStudy2ShoppingWeb' %>
    <p> Trung tâm mua sắm trực tuyến</p>
    <br>
    <div class="footer-content">
      <div class="row">
        <div class="col-xs-12 col-md-6">
          <h5>
            Email: 
            <a href="mailto:hufi@ittc@.com" title="hufi@ittc.com">hufi@ittc.com</a>
            <br>
            Hotline: 
            <a href="tel:(+84)357502346" title="Shop PhoneNumber">(+84)357502346</a>
          </h5>
          <h5>Trợ Giúp &amp; Tư Vấn</h5>
          <ul class="list-footer">
            <li> <a href="https://www.google.com" title="lien he">Liên hệ</a> </li>
            <li> <a href="https://www.google.com" title="ban do">Bản đồ</a> </li>
            <li> <a href="https://www.google.com" title="cach chon size quan ao">Cách chọn size quần áo</a> </li>
            <li> <a href="https://www.google.com" title="cau hoi thuong gap">Câu hỏi thường gặp</a> </li>
            <li> <a href="https://www.google.com" title="chinh sach khach vip">Chính sách khách VIP</a> </li>
            <li> <a href="https://www.google.com" title="chinh sach giao hang">Chính sách giao hàng</a> </li>
            <li> <a href="https://www.google.com" title="chinh sach doi hang">Chính sách đổi hàng</a> </li>
          </ul>
        </div>
        <div class="col-xs-5 col-md-6">
          <h5>Địa Chỉ Showroom</h5>
          140 Lê Trọng Tấn, Phường Tây Thạnh, Quận Tân Phú, Hồ Chí Minh
          <br><br>
          <h5>Chủ quản: HUFI STORE
            <br>
            MST cá nhân: 89898989898989
            <br>
            Số ĐKKD: 88888888 do UBND Quận Tân Phú - TP.HCM cấp ngày 01/01/2020
          </h5>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/common/_header.html.erb
<div class="navbar navbar-expand-lg" id="navbarText">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"><i class="fas fa-bars" style="color:#fff; font-size:28px;"></i></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item">
        <%= link_to 'Trang Chủ', root_path , {class: 'nav-link'}%>
      </li>
      <li class="nav-item">
        <%= link_to 'Sale', sanphams_path(pro: 'Sale') , {class: 'nav-link'}%>
      </li>
      <%@category.each do |cate|%>
        <li class="nav-item">
          <div class="dropdown">
            <div id="navbarDropdownMenuLink">
              <%= link_to cate.tendanhmuc, sanphams_path(sex: cate.tendanhmuc) , class:"nav-link dropdown-toggle"%>
            </div>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <%cate.loaisanphams.each do |type|%>
                <%= link_to type.tenloai, sanphams_path(id: type.maloai, sex: cate.tendanhmuc, name: type.tenloai), {class: 'dropdown-item'}%>
              <%end%>
            </div>
          </div>
        </li>
      <%end%>
      <li class="nav-item">
        <div class="dropdown">
          <div id="navbarDropdownMenuLink">
            <%= link_to 'Thương Hiệu', sanphams_path, class:"nav-link dropdown-toggle"%>
          </div>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <%@brand.each do |br|%>
              <%= link_to br.tenthuonghieu, sanphams_path(brand: br.tenthuonghieu), {class: 'dropdown-item'}%>
            <%end%>
          </div>
        </div>
      </li>
    </ul>
  </div>
  <form class="form-inline my-2 my-lg-0">
    <form class="form-inline d-flex justify-content-center md-form form-sm ">
      <input id="tags" class="form-control form-control-sm mr-3 col-md-auto" type="text" aria-label="Search" size=40 style="width: auto; margin-bottom:10px; margin-top:10px" >
    </form>
    <div class="nav-item" >
      <%= link_to image_tag("cart_.png", class: 'img_cart' ,'aria-hidden' => true), carts_path, {:action=>"show", :controller=>"carts"}%>
      <div class= "rounded-circle">
        <span id="cart"
            <% if session[:cart].nil? %>
                0
            <% end %>
              >
          <% unless session[:cart].nil?%>
            <%= session[:cart].length%>
          <% end %>
        </span>
      </div>
    </div>
    <div>
      <%if khachhang_signed_in?%>
        <div class="dropdown">
          <div id="navbarDropdownMenuLink">
            <%= form_for current_khachhang, url: khachhangs_update_info_path, html: { method: :put } do |f|%>
              <% if current_khachhang.anhdaidien.file.nil? %>
                <%= image_tag("user.png", class:"img  img-thumbnail")%>
              <%else%>
                <%= image_tag(current_khachhang.anhdaidien, class:"img  img-thumbnail ")%>
              <%end%>
            <%end%>
          </div>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
            <%= link_to 'Tài Khoản', khachhangs_profile_path, class: 'dropdown-item'%>
            <%= link_to 'Đơn Hàng', dondathangs_path, class: 'dropdown-item'%>
            <div class="dropdown-divider"></div>
            <%= link_to 'Đăng Xuất', destroy_khachhang_session_path, method: :delete , class: 'dropdown-item'%>
          </div>
        </div>
      <%else%>
        <%= link_to 'Đăng Nhập', new_khachhang_session_path, class: 'nav-link' ,style: 'margin-top:5px; white-space: nowrap;'%>
      <%end%>
    </div>
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="nav-link"></a>
      </li>
      <li class="nav-item">
        <a class="nav-link"></a>
      </li>
    </ul>
  </form>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DoAn</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'scroll', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>

    <a class="scrollToTop"><i class="fa fa-arrow-up"></i></a>
  </head>
  <body >
    <%=render "common/header"%>
    <div class="main main-container" style= " min-height: 600px;">
      <%= yield %>
      <br>
    </div>
    <%=render "common/footer"%>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Do An</title>
    <%= csrf_meta_tags %>
    <!-- Bootstrap CSS -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!--Fontawesome CDN-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
  </head>
  <body >
    <%= yield %>
  </body>
</html>